name: Build and Release GKI Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      build_a12_510:
        description: "Build a12 5.10?"
        required: true
        type: boolean
        default: false
      build_a13_510:
        description: "Build a13 5.10?"
        required: true
        type: boolean
        default: false
      build_a13_515:
        description: "Build a13 5.15?"
        required: true
        type: boolean
        default: false
      build_a14_515:
        description: "Build a14 5.15?"
        required: true
        type: boolean
        default: false
      build_a14_61:
        description: "Build a14 6.1?"
        required: true
        type: boolean
        default: false
      build_a15_66:
        description: "Build a15  6.6?"
        required: true
        type: boolean
        default: true
      make_release:
        description: "Do you want to create a release?"
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        description: "Choose KernelSU"
        required: true
        type: choice
        options:
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "Choose ksu branch"
        required: true
        type: choice
        options:
          - Stable
          - Dev
          - Other
        default: Dev
      kernelsu_branch_other:
        description: "If 'Other' is selected, specify your custom branch"
        required: false
        type: string
        default: ""

jobs:
  build-kernel-a12-5-10:
    if: ${{ inputs.build_a12_510 }}
    uses: ./.github/workflows/kernel-a12-5.10.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  build-kernel-a13-5-10:
    if: ${{ inputs.build_a13_510 }}
    uses: ./.github/workflows/kernel-a13-5.10.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  build-kernel-a13-5-15:
    if: ${{ inputs.build_a13_515 }}
    uses: ./.github/workflows/kernel-a13-5.15.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  build-kernel-a14-5-15:
    if: ${{ inputs.build_a14_515 }}
    uses: ./.github/workflows/kernel-a14-5.15.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  build-kernel-a14-6-1:
    if: ${{ inputs.build_a14_61 }}
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  build-kernel-a15-6-6:
    if: ${{ inputs.build_a15_66 }}
    uses: ./.github/workflows/kernel-a15-6.6.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other }}

  trigger-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    needs:
      - build-kernel-a12-5-10
      - build-kernel-a13-5-10
      - build-kernel-a13-5-15
      - build-kernel-a14-5-15
      - build-kernel-a14-6-1
      - build-kernel-a15-6-6
    if: ${{ inputs.make_release }}
    env:
      REPO_OWNER: MiRinFork
      REPO_NAME: GKI_SukiSU_SUSFS
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      RELEASE_NOTES: |
        > [!CAUTION]
        > Take your own risk! Nobody tested. `fastboot boot` before flash it.

        Features:
        - ${{ inputs.kernelsu_variant }} (${{ inputs.kernelsu_branch }})
        - Manual Syscall Hooks
        - Wireguard Support
        - BBR Support
        - [baseband_guard.c](https://github.com/vc-teahouse/Baseband-guard/blob/main/baseband_guard.c) added

        Usage: 
          - Use Kernel Flasher (capntrips).
          - Flash AnyKernel3 zip file.

    steps:
      - name: Get current date
        id: date
        run: |
          echo "currentdate=$(date +"%Y-%m-%d-%H-%M-%S")" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine the branch for KernelSU-${{ inputs.kernelsu_variant }}
        if: ${{ inputs.kernelsu_branch == 'Dev' || inputs.kernelsu_variant == 'SukiSU' }}
        run: |
          if [[ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]]; then
            BRANCH="main"
          elif [[ "${{ inputs.kernelsu_branch }}" == "Other" && -n "${{ inputs.kernelsu_branch_other }}" ]]; then
            BRANCH="${{ inputs.kernelsu_branch_other }}"
          else
            echo "Error: Custom branch not provided for 'Other'" >&2
            exit 1
          fi
          echo "KSU_BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Get commit hash or tag and generate URL for KernelSU-${{ inputs.kernelsu_variant }}
        run: |
          if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
            REPO_URL="https://github.com/SukiSU-Ultra/SukiSU-Ultra.git"
            REPO_URL2="SukiSU-Ultra/SukiSU-Ultra"
          fi
          COMMIT_HASH=$(git ls-remote $REPO_URL refs/heads/$KSU_BRANCH | awk '{ print $1 }')
          KSU_REF=$COMMIT_HASH
          KSU_URL="https://github.com/$REPO_URL2/commit/$COMMIT_HASH"
          echo "KSU_REF=$KSU_REF" >> $GITHUB_ENV
          echo "KSU_URL=$KSU_URL" >> $GITHUB_ENV

      - name: Get commit hashes and generate commit URLs
        run: |
          GITLAB_OWNER="simonpunk"
          GITLAB_REPO="susfs4ksu"
          declare -A BRANCH_MAP=(
            ["gki_android15_6_6"]="gki-android14-6.1" 
          )
          for var_name in "${!BRANCH_MAP[@]}"; do
            branch_name="${BRANCH_MAP[$var_name]}"
            COMMIT_HASH=$(git ls-remote https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO.git refs/heads/$branch_name | awk '{ print $1 }')
            if [[ -n "$COMMIT_HASH" ]]; then
              COMMIT_URL="https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO/-/commit/$COMMIT_HASH"
              echo "COMMIT_HASH_${var_name}=$COMMIT_HASH" >> "$GITHUB_ENV"
              echo "COMMIT_URL_${var_name}=$COMMIT_URL" >> "$GITHUB_ENV"
            fi
          done

      - name: Append Commit Hashes & Links to RELEASE_NOTES
        run: |
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "" >> $GITHUB_ENV
          echo "- KernelSU: [$KSU_REF]($KSU_URL)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate and Create New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          NEW_TAG=${{ env.currentdate }}
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push --tags

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.currentdate }}
          prerelease: true
          release_name: ${{ env.currentdate }}
          body: ${{ env.RELEASE_NOTES }}

      - name: Upload Release Assets Dynamically
        run: |
          for file in ./downloaded-artifacts/kernel-*/*; do
              if [ -d "$file" ]; then continue; fi
              gh release upload ${{ env.NEW_TAG }} "$file"
          done
